import { NextApiRequest, NextApiResponse } from "next";
import { StoreProduct } from "../../../type";
const stripe = require("stripe")(process.env.STRIPE_SECRET_KEY);

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const { items, email } = req.body;
  const modifiedItems = items.map((item: StoreProduct) => ({
    quantity: item.quantity,
    price_data: {
      currency: "usd",
      unit_amount: item.price * 100,
      product_data: {
        name: item.title,
        description: item.description,
        images: [item.image],
      },
    },
  }));
  const session = await stripe.checkout.sessions.create({
    payment_method_types: ["card"],
    shipping_address_collection: {
      allowed_countries: ["US",
      "AE",
      "AG",
      "AL",
      "AM",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "CA",
      "CH",
      "CI",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "EC",
      "EE",
      "EG",
      "ES",
      "ET",
      "FI",
      "FR",
      "GB",
      "GH",
      "GM",
      "GR",
      "GT",
      "GY",
      "HK",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KH",
      "KR",
      "KW",
      "LC",
      "LI",
      "LK",
      "LT",
      "LU",
      "LV",
      "MA",
      "MD",
      "MG",
      "MK",
      "MN",
      "MO",
      "MT",
      "MU",
      "MX",
      "MY",
      "NA",
      "NG",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RW",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SN",
      "SV",
      "TH",
      "TN",
      "TR",
      "TT",
      "TZ",
      "UY",
      "UZ",
      "VN",
      "ZA",
      "BD",
      "BJ",
      "MC",
      "NE",
      "SM",
      "AZ",
      "BN",
      "BT",
      "AO",
      "DZ",
      "TW",
      "BS",
      "BW",
      "GA",
      "LA",
      "MZ",
      "KZ"],
    },
    line_items: modifiedItems,
    mode: "payment",
    success_url: `${process.env.NEXTAUTH_URL}/success`,
    cancel_url: `${process.env.NEXTAUTH_URL}/checkout`,
    metadata: {
      email,
      images: JSON.stringify(items.map((item: any) => item.image)),
    },
  });
  res.status(200).json({
    id: session.id,
  });
}
